[package]
name = "ESPeyboard"
version = "0.1.0"
edition = "2024"

[dependencies]
btleplug = "0.11.8"
evdev-rs = "0.6.1"
futures = "0.3.31"
polling = "3.7.4"
tokio = { version = "1.45.1", features = ["full"] }
uuid = "1.17.0"
